spring.application.name=Product-Service

server.servlet.context-path=/api/v1

logging.pattern.console=%d{HH:mm:ss} %-5level %logger{20} - %msg%n

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=${RABBIT_HOST}172.25.253.208
spring.rabbitmq.port=${RABBIT_PORT}5672
spring.rabbitmq.username=${RABBIT_USER}guest
spring.rabbitmq.password=${RABBIT_PSW}guest